### ISSUE TITLE
Set-up input files fileformat

### ISSUE THREAD

**Issue by jurjendejong** [Deltares/AppendixVisualiser#1]
Input file consists of:
* Descriptions of datasets and additional settings for the page (YAML-format)
* Data to be plotted (JSON format) (one file per dataset)

The yaml-structure is structured as

```
pagesettings:  # Other settings to be included on the page?
  header: PAV! (Pilot Appendix Visualiser)
  text: This is a test for building quick interactive web visualisations from preprocessed model results.

datasets:  # Independent datasets
  dataset1_name:
    ylabel: label for yaxis
    filename: dataset1.json
    
  dataset2_name:
    ylabel: label for yaxis
    filename: dataset2.json
```

The json structure is structured as:

```
{'station1': 
   'label1': {time: [], data: []},
   'label2': {time: [], data: []},
   'label3': {time: [], data: []},
'station2': 
   'label1': {time: [], data: []},
   'label2': {time: [], data: []},
   'label3': {time: [], data: []},
}
```
